# Base configs
baseurl:""

# UI configs
title: "Hardik Narendra"
author: "Hardik Narendra"
about: "Programmer"
social_urls:
  facebook: "https://www.facebook.com/Hardik Narendra"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
